sudo: false
language: "node_js"
node_js:
  - node
  - 6
services:
  - mongodb
install:
  - npm install bower
  - npm install
  - node_modules/bower/bin/bower install
before_script:
  # Virtual screen for firefox to execute Karma tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: grunt
after_success: grunt jshint
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
