sudo: false
language: "node_js"
node_js:
  - node
  - 6
services:
  - mongodb

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
