sudo: false
language: "node_js"
node_js:
  - node
  - 7
services:
  - mongodb
install: yarn && jspm i
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success: gulp coveralls
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
